version: '3.8'

services:
  portainer:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: portainer/portainer-ce
    environment:
      - PUID=${UID}
      - PGID=${GID}
    privileged: true
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    networks:
      - default

networks:
  default: