version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    environment:
      - PUID=${UID}
      - PGID=${GID}
    privileged: true
    ports:
      - "${PORTAINER_PORT:-9443}:9443"
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
